[package]
name = "Reclaim"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
macroquad-text = "0.2.0"

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad.git", branch = "render_target_params"}